<?php

namespace Database\Seeders;

use App\Models\Role;
use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\PermissionRegistrar;

class RolesAndPermissionsSeeder extends Seeder
{
    public function run(): void
    {
        app(PermissionRegistrar::class)->forgetCachedPermissions();

        $permissions = [
            'dashboard.view',
            'users.view',
            'users.create',
            'users.update',
            'users.delete',
            'roles.assign',
            'roles.view',
            'roles.create',
            'roles.update',
            'roles.delete',
            'akaun.view',
            'akaun.create',
            'akaun.update',
            'akaun.delete',
            'hasil.view',
            'hasil.create',
            'hasil.update',
            'hasil.delete',
            'belanja.view',
            'belanja.create',
            'belanja.update',
            'belanja.delete',
            'sumber_hasil.view',
            'sumber_hasil.create',
            'sumber_hasil.update',
            'sumber_hasil.delete',
            'kategori_belanja.view',
            'kategori_belanja.create',
            'kategori_belanja.update',
            'kategori_belanja.delete',
            'tabung_khas.view',
            'tabung_khas.create',
            'tabung_khas.update',
            'tabung_khas.delete',
            'program_masjid.view',
            'program_masjid.create',
            'program_masjid.update',
            'program_masjid.delete',
            'pindahan_akaun.view',
            'pindahan_akaun.create',
            'pindahan_akaun.update',
            'pindahan_akaun.delete',
            'running_no.view',
            'running_no.generate',
            'running_no.update',
            'masjid.view',
            'masjid.create',
            'masjid.update',
            'masjid.delete',
            'finance.view',
            'finance.create',
            'finance.update',
            'finance.approve',
            'reports.view',
            'reports.export',
            'view laporan buku tunai',
            'view laporan jumaat',
            'view laporan derma',
            'view laporan belanja',
            'subscriptions.manage',
            'cms.manage',
            'settings.manage',
            'audit.view',
        ];

        foreach ($permissions as $name) {
            Permission::findOrCreate($name, 'web');
        }

        $roles = [
            // level 1 — system (global, protected)
            'Superadmin' => array_values(array_unique([
                ...$permissions,
                'view laporan buku tunai',
            ])),

            // level 2 — tenant admin (global, assigned per-masjid context)
            // Admin manages their own masjid's users, roles, and finance.
            // Does NOT receive system-level permissions (subscriptions, CMS, global masjid CRUD).
            'Admin' => [
                'dashboard.view',
                'users.view',
                'users.create',
                'users.update',
                'users.delete',
                'roles.assign',
                'roles.view',
                'roles.create',
                'roles.update',
                'roles.delete',
                'akaun.view',
                'akaun.create',
                'akaun.update',
                'akaun.delete',
                'hasil.view',
                'hasil.create',
                'hasil.update',
                'hasil.delete',
                'belanja.view',
                'belanja.create',
                'belanja.update',
                'belanja.delete',
                'sumber_hasil.view',
                'sumber_hasil.create',
                'sumber_hasil.update',
                'sumber_hasil.delete',
                'kategori_belanja.view',
                'kategori_belanja.create',
                'kategori_belanja.update',
                'kategori_belanja.delete',
                'tabung_khas.view',
                'tabung_khas.create',
                'tabung_khas.update',
                'tabung_khas.delete',
                'program_masjid.view',
                'program_masjid.create',
                'program_masjid.update',
                'program_masjid.delete',
                'pindahan_akaun.view',
                'pindahan_akaun.create',
                'pindahan_akaun.update',
                'pindahan_akaun.delete',
                'running_no.view',
                'running_no.generate',
                'running_no.update',
                'masjid.view',
                'masjid.update',
                'finance.view',
                'finance.create',
                'finance.update',
                'finance.approve',
                'reports.view',
                'reports.export',
                'view laporan buku tunai',
                'view laporan jumaat',
                'view laporan derma',
                'view laporan belanja',
                'audit.view',
            ],

            // level 3 — user roles below (restricted permission subsets)
            'Manager' => [
                'dashboard.view',
                'users.view',
                'users.update',
                'roles.assign',
                'roles.view',
                'masjid.view',
                'masjid.update',
                'hasil.view',
                'belanja.view',
                'pindahan_akaun.view',
                'pindahan_akaun.create',
                'pindahan_akaun.update',
                'pindahan_akaun.delete',
                'running_no.view',
                'running_no.generate',
                'finance.view',
                'finance.create',
                'finance.update',
                'finance.approve',
                'reports.view',
                'reports.export',
                'audit.view',
            ],
            'FinanceOfficer' => [
                'dashboard.view',
                'hasil.view',
                'hasil.create',
                'hasil.update',
                'hasil.delete',
                'belanja.view',
                'belanja.create',
                'belanja.update',
                'belanja.delete',
                'pindahan_akaun.view',
                'pindahan_akaun.create',
                'pindahan_akaun.update',
                'pindahan_akaun.delete',
                'running_no.view',
                'running_no.generate',
                'finance.view',
                'finance.create',
                'finance.update',
                'finance.approve',
                'reports.view',
                'masjid.view',
            ],
            'Bendahari' => [
                'dashboard.view',
                'users.view',
                'users.update',
                'hasil.view',
                'hasil.create',
                'hasil.update',
                'hasil.delete',
                'belanja.view',
                'belanja.create',
                'belanja.update',
                'belanja.delete',
                'finance.view',
                'akaun.view',
                'akaun.create',
                'akaun.update',
                'akaun.delete',
                'sumber_hasil.view',
                'sumber_hasil.create',
                'sumber_hasil.update',
                'sumber_hasil.delete',
                'kategori_belanja.view',
                'kategori_belanja.create',
                'kategori_belanja.update',
                'kategori_belanja.delete',
                'tabung_khas.view',
                'tabung_khas.create',
                'tabung_khas.update',
                'tabung_khas.delete',
                'program_masjid.view',
                'program_masjid.create',
                'program_masjid.update',
                'program_masjid.delete',
                'pindahan_akaun.view',
                'pindahan_akaun.create',
                'pindahan_akaun.update',
                'pindahan_akaun.delete',
                'running_no.view',
                'running_no.generate',
                'running_no.update',
                'finance.create',
                'finance.update',
                'finance.approve',
                'reports.view',
                'reports.export',
                'view laporan buku tunai',
                'view laporan jumaat',
                'view laporan derma',
                'view laporan belanja',
                'masjid.view',
            ],
            'AJK' => [
                'dashboard.view',
                'users.view',
                'akaun.view',
                'hasil.view',
                'belanja.view',
                'sumber_hasil.view',
                'kategori_belanja.view',
                'tabung_khas.view',
                'program_masjid.view',
                'pindahan_akaun.view',
                'finance.view',
                'running_no.view',
                'reports.view',
                'masjid.view',
            ],
            'Auditor' => [
                'dashboard.view',
                'audit.view',
                'reports.view',
                'reports.export',
                'view laporan buku tunai',
                'view laporan jumaat',
                'view laporan derma',
                'view laporan belanja',
                'users.view',
                'masjid.view',
                'finance.view',
            ],
            'MasjidOfficer' => [
                'dashboard.view',
                'masjid.view',
                'finance.view',
                'finance.create',
                'reports.view',
            ],
            'User' => [
                'dashboard.view',
                'reports.view',
            ],
        ];

        foreach ($roles as $roleName => $rolePermissions) {
            // Level 1 = Superadmin (system-reserved, immutable)
            // Level 2 = Admin (tenant administrator)
            // Level 3 = all other user roles
            $level = match ($roleName) {
                'Superadmin' => 1,
                'Admin'      => 2,
                default      => 3,
            };

            $role = Role::firstOrCreate(
                ['name' => $roleName, 'guard_name' => 'web'],
                ['level' => $level, 'masjid_id' => null]
            );

            // Ensure level is set correctly on existing records
            if ((int) $role->level !== $level) {
                $role->update(['level' => $level]);
            }

            $role->syncPermissions($rolePermissions);
        }
    }
}
