<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;
use Spatie\Permission\PermissionRegistrar;

class RolesAndPermissionsSeeder extends Seeder
{
    public function run(): void
    {
        app(PermissionRegistrar::class)->forgetCachedPermissions();

        $permissions = [
            'dashboard.view',
            'users.view',
            'users.create',
            'users.update',
            'users.delete',
            'roles.assign',
            'akaun.view',
            'akaun.create',
            'akaun.update',
            'akaun.delete',
            'hasil.view',
            'hasil.create',
            'hasil.update',
            'hasil.delete',
            'belanja.view',
            'belanja.create',
            'belanja.update',
            'belanja.delete',
            'sumber_hasil.view',
            'sumber_hasil.create',
            'sumber_hasil.update',
            'sumber_hasil.delete',
            'kategori_belanja.view',
            'kategori_belanja.create',
            'kategori_belanja.update',
            'kategori_belanja.delete',
            'tabung_khas.view',
            'tabung_khas.create',
            'tabung_khas.update',
            'tabung_khas.delete',
            'program_masjid.view',
            'program_masjid.create',
            'program_masjid.update',
            'program_masjid.delete',
            'pindahan_akaun.view',
            'pindahan_akaun.create',
            'pindahan_akaun.update',
            'pindahan_akaun.delete',
            'running_no.view',
            'running_no.generate',
            'running_no.update',
            'masjid.view',
            'masjid.create',
            'masjid.update',
            'masjid.delete',
            'finance.view',
            'finance.create',
            'finance.update',
            'finance.approve',
            'reports.view',
            'reports.export',
            'subscriptions.manage',
            'cms.manage',
            'settings.manage',
            'audit.view',
        ];

        foreach ($permissions as $name) {
            Permission::findOrCreate($name, 'web');
        }

        $roles = [
            'Admin' => $permissions,
            'Manager' => [
                'dashboard.view',
                'users.view',
                'users.update',
                'roles.assign',
                'masjid.view',
                'masjid.update',
                'hasil.view',
                'belanja.view',
                'pindahan_akaun.view',
                'pindahan_akaun.create',
                'pindahan_akaun.update',
                'pindahan_akaun.delete',
                'running_no.view',
                'running_no.generate',
                'finance.view',
                'finance.create',
                'finance.update',
                'finance.approve',
                'reports.view',
                'reports.export',
                'audit.view',
            ],
            'FinanceOfficer' => [
                'dashboard.view',
                'hasil.view',
                'hasil.create',
                'hasil.update',
                'hasil.delete',
                'belanja.view',
                'belanja.create',
                'belanja.update',
                'belanja.delete',
                'pindahan_akaun.view',
                'pindahan_akaun.create',
                'pindahan_akaun.update',
                'pindahan_akaun.delete',
                'running_no.view',
                'running_no.generate',
                'finance.view',
                'finance.create',
                'finance.update',
                'finance.approve',
                'reports.view',
                'masjid.view',
            ],
            'Bendahari' => [
                'dashboard.view',
                'users.view',
                'users.update',
                'hasil.view',
                'hasil.create',
                'hasil.update',
                'hasil.delete',
                'belanja.view',
                'belanja.create',
                'belanja.update',
                'belanja.delete',
                'finance.view',
                'akaun.view',
                'akaun.create',
                'akaun.update',
                'akaun.delete',
                'sumber_hasil.view',
                'sumber_hasil.create',
                'sumber_hasil.update',
                'sumber_hasil.delete',
                'kategori_belanja.view',
                'kategori_belanja.create',
                'kategori_belanja.update',
                'kategori_belanja.delete',
                'tabung_khas.view',
                'tabung_khas.create',
                'tabung_khas.update',
                'tabung_khas.delete',
                'program_masjid.view',
                'program_masjid.create',
                'program_masjid.update',
                'program_masjid.delete',
                'pindahan_akaun.view',
                'pindahan_akaun.create',
                'pindahan_akaun.update',
                'pindahan_akaun.delete',
                'running_no.view',
                'running_no.generate',
                'running_no.update',
                'finance.create',
                'finance.update',
                'finance.approve',
                'reports.view',
                'reports.export',
                'masjid.view',
            ],
            'AJK' => [
                'dashboard.view',
                'users.view',
                'akaun.view',
                'hasil.view',
                'belanja.view',
                'sumber_hasil.view',
                'kategori_belanja.view',
                'tabung_khas.view',
                'program_masjid.view',
                'pindahan_akaun.view',
                'finance.view',
                'running_no.view',
                'reports.view',
                'masjid.view',
            ],
            'Auditor' => [
                'dashboard.view',
                'audit.view',
                'reports.view',
                'reports.export',
                'users.view',
                'masjid.view',
                'finance.view',
            ],
            'MasjidOfficer' => [
                'dashboard.view',
                'masjid.view',
                'finance.view',
                'finance.create',
                'reports.view',
            ],
            'User' => [
                'dashboard.view',
                'reports.view',
            ],
        ];

        foreach ($roles as $roleName => $rolePermissions) {
            $role = Role::findOrCreate($roleName, 'web');
            $role->syncPermissions($rolePermissions);
        }
    }
}
