<?php

return [
    [
        'group_key' => 'menu.group_general',
        'title_key' => 'menu.dashboard',
        'route' => 'dashboard',
        'icon' => 'home',
        'permission' => ['view dashboard', 'dashboard.view'],
        'tenant_scoped' => false,
    ],
    [
        'group_key' => 'menu.group_finance',
        'title_key' => 'menu.akaun',
        'route' => ['akaun.index', 'admin.akaun.index'],
        'icon' => 'wallet',
        'permission' => ['manage akaun', 'akaun.view'],
    ],
    [
        'group_key' => 'menu.group_finance',
        'title_key' => 'menu.hasil',
        'route' => ['hasil.index', 'admin.hasil.index'],
        'icon' => 'arrow-down',
        'permission' => ['manage hasil', 'hasil.view'],
    ],
    [
        'group_key' => 'menu.group_finance',
        'title_key' => 'menu.belanja',
        'route' => ['belanja.index', 'admin.belanja.index'],
        'icon' => 'arrow-up',
        'permission' => ['manage belanja', 'belanja.view'],
    ],
    [
        'group_key' => 'menu.group_finance',
        'title_key' => 'menu.bank_import',
        'route' => ['admin.bank.import.index'],
        'icon' => 'file',
        'permission' => ['bank_import.access', 'hasil.create', 'belanja.create'],
    ],
    [
        'group_key' => 'menu.group_finance',
        'title_key' => 'menu.bank_pdf_import',
        'route' => ['admin.bank.pdf-import.index'],
        'icon' => 'file',
        'permission' => ['bank_import.access', 'hasil.create', 'belanja.create'],
    ],
    [
        'group_key' => 'menu.group_finance',
        'title_key' => 'menu.baucar',
        'route' => ['baucar.index'],
        'icon' => 'file',
        'permission' => ['approve baucar'],
    ],
    [
        'group_key' => 'menu.group_laporan',
        'title_key' => 'menu.laporan_buku_tunai',
        'route' => ['laporan.buku-tunai'],
        'icon' => 'chart',
        'permission' => ['view laporan buku tunai'],
    ],
    [
        'group_key' => 'menu.group_laporan',
        'title_key' => 'menu.laporan_kutipan_jumaat',
        'route' => ['laporan.jumaat'],
        'icon' => 'chart',
        'permission' => ['view laporan jumaat'],
    ],
    [
        'group_key' => 'menu.group_laporan',
        'title_key' => 'menu.laporan_derma',
        'route' => ['laporan.derma'],
        'icon' => 'chart',
        'permission' => ['view laporan derma'],
    ],
    [
        'group_key' => 'menu.group_laporan',
        'title_key' => 'menu.laporan_belanja',
        'route' => ['laporan.belanja'],
        'icon' => 'chart',
        'permission' => ['view laporan belanja'],
    ],
    [
        'group_key' => 'menu.group_laporan',
        'title_key' => 'menu.laporan_penyata',
        'route' => ['laporan.penyata'],
        'icon' => 'chart',
        'permission' => ['view laporan penyata'],
    ],
    [
        'group_key' => 'menu.group_laporan',
        'title_key' => 'menu.laporan_tabung_khas',
        'route' => ['laporan.tabung', 'laporan.tabung.detail'],
        'icon' => 'chart',
        'permission' => ['view laporan tabung'],
    ],
    [
        'group_key' => 'menu.group_laporan',
        'title_key' => 'menu.laporan_sedia_ada',
        'route' => ['report.index', 'admin.reporting.index'],
        'icon' => 'chart',
        'permission' => ['view report', 'reports.view'],
    ],
    [
        'group_key' => 'menu.group_administration',
        'title_key' => 'menu.pengguna',
        'route' => ['user.index', 'admin.users.index'],
        'icon' => 'users',
        'permission' => ['manage users', 'users.view'],
    ],
    [
        'group_key' => 'menu.group_administration',
        'title_key' => 'menu.roles',
        'route' => ['admin.roles.index'],
        'icon' => 'shield',
        'permission' => ['roles.assign', 'roles.view'],
    ],
    [
        'group_key' => 'menu.group_administration',
        'title_key' => 'menu.langganan',
        'route' => ['admin.subscriptions.index'],
        'icon' => 'credit-card',
        'permission' => ['subscriptions.manage'],
        'tenant_scoped' => false,
    ],
    [
        'group_key' => 'menu.group_superadmin',
        'title_key' => 'menu.sumber_hasil',
        'route' => ['admin.sumber-hasil.index'],
        'icon' => 'tag',
        'permission' => ['sumber_hasil.view'],
    ],
    [
        'group_key' => 'menu.group_superadmin',
        'title_key' => 'menu.tabung_khas',
        'route' => ['admin.tabung-khas.index'],
        'icon' => 'archive',
        'permission' => ['tabung_khas.view'],
    ],
    [
        'group_key' => 'menu.group_superadmin',
        'title_key' => 'menu.kategori_belanja',
        'route' => ['admin.kategori-belanja.index'],
        'icon' => 'list',
        'permission' => ['kategori_belanja.view'],
    ],
    [
        'group_key' => 'menu.group_superadmin',
        'title_key' => 'menu.pindahan_akaun',
        'route' => ['admin.pindahan-akaun.index'],
        'icon' => 'switch-horizontal',
        'permission' => ['pindahan_akaun.view'],
    ],
    [
        'group_key' => 'menu.group_superadmin',
        'title_key' => 'menu.running_no',
        'route' => ['admin.running-no.index'],
        'icon' => 'hashtag',
        'permission' => ['running_no.view'],
    ],
    [
        'group_key' => 'menu.group_superadmin',
        'title_key' => 'menu.cms',
        'route' => ['admin.cms.builder.edit'],
        'icon' => 'file-text',
        'permission' => ['cms.manage'],
        'superadmin_only' => false,
        'tenant_scoped' => true,
    ],
    [
        'group_key' => 'menu.group_superadmin',
        'title_key' => 'menu.system_settings',
        'route' => ['admin.settings.index'],
        'icon' => 'cog',
        'permission' => ['superadmin'],
        'superadmin_only' => true,
        'tenant_scoped' => false,
    ],
];
